from tkinter import*
r = Tk()
r.title('Entry demo')
Label(r,text='First Name').grid(row=0)
e1 = Entry(r)
e1 . grid(row=0,column=1)
Label(r,text='last Name').grid(row=1)
e2 = Entry(r)
e2. grid(row=1,column=1)
mainloop()
